package agent

import (
	"bytes"
	"encoding/json"
	"os"
	"testing"

	"github.com/ThanabordeeN/AgentRD2/runtime-go/internal/domain"
	"github.com/ThanabordeeN/AgentRD2/runtime-go/internal/tools"
)

// decodeFixture reads a JSON fixture while preserving integer/float typing
// through json.Number, so the Go prompt renderer sees the same numeric types
// Python's json.load produces.
func decodeFixture[T any](t *testing.T, path string) T {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read fixture %s: %v", path, err)
	}
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.UseNumber()
	var decoded T
	if err := decoder.Decode(&decoded); err != nil {
		t.Fatalf("decode fixture %s: %v", path, err)
	}
	return decoded
}

// agentContextFromMap builds a domain.AgentContext from a fixture map.
func agentContextFromMap(raw map[string]any) *domain.AgentContext {
	agentContext := domain.NewAgentContext(domain.StringFrom(raw["npc_id"]))
	if profile, ok := raw["profile"].(map[string]any); ok {
		agentContext.Profile = profile
	}
	agentContext.WorldState = domain.MapFrom(raw["world_state"])
	if goal, ok := raw["current_goal"].(string); ok {
		agentContext.CurrentGoal = &goal
	}
	if _, present := raw["current_mood"]; present {
		agentContext.CurrentMood = domain.StringFrom(raw["current_mood"])
	}
	agentContext.RecentEvents = domain.MapsFrom(raw["recent_events"])
	agentContext.RetrievedEvents = domain.MapsFrom(raw["retrieved_events"])
	agentContext.WikiContext = domain.MapsFrom(raw["wiki_context"])
	agentContext.QuestContext = domain.MapFrom(raw["quest_context"])
	agentContext.AvailableTools = domain.StringsFrom(raw["available_tools"])
	agentContext.Flags = domain.MapFrom(raw["flags"])
	return agentContext
}

// TestBuildAgentPromptMatchesPython asserts byte-for-byte parity with
// runtime/agent/instructions.py::build_agent_prompt. The expected strings in
// testdata/prompt_expected.json were generated by running that Python function
// over the contexts in testdata/prompt_cases.json.
func TestBuildAgentPromptMatchesPython(t *testing.T) {
	cases := decodeFixture[map[string]map[string]any](t, "testdata/prompt_cases.json")
	expected := decodeFixture[map[string]string](t, "testdata/prompt_expected.json")
	if len(cases) == 0 || len(expected) == 0 {
		t.Fatal("prompt fixtures are empty")
	}
	for name, raw := range cases {
		t.Run(name, func(t *testing.T) {
			want, ok := expected[name]
			if !ok {
				t.Fatalf("no expected prompt for case %q", name)
			}
			got := BuildAgentPrompt(agentContextFromMap(raw))
			if got != want {
				t.Errorf("prompt mismatch for %q\n--- want ---\n%s\n--- got ---\n%s", name, want, got)
			}
		})
	}
}

// TestBuildAgentPromptOmitsEmptySections pins the section omission rules.
func TestBuildAgentPromptOmitsEmptySections(t *testing.T) {
	agentContext := domain.NewAgentContext("npc_001")
	agentContext.Profile = map[string]any{"name": "Elias"}
	agentContext.WorldState = map[string]any{}
	prompt := BuildAgentPrompt(agentContext)

	for _, unwanted := range []string{
		"NPC SYSTEM PROMPT",
		"WORLD LORE CONTEXT",
		"CURRENT QUEST CONTEXT",
		"DIALOGUE-ONLY MODE",
		"RETRIEVED TIMELINE EVENTS",
	} {
		if bytes.Contains([]byte(prompt), []byte(unwanted)) {
			t.Errorf("prompt unexpectedly contains %q:\n%s", unwanted, prompt)
		}
	}
	for _, wanted := range []string{
		"NPC PROFILE",
		"CURRENT WORLD STATE",
		"CURRENT GOAL\n(none)",
		"CURRENT MOOD\nneutral",
		"RECENT EVENTS",
		"AVAILABLE TOOLS\n(none)",
		"ACTION ARGUMENT RULES",
	} {
		if !bytes.Contains([]byte(prompt), []byte(wanted)) {
			t.Errorf("prompt missing %q:\n%s", wanted, prompt)
		}
	}
}

// TestBuildAgentPromptNilContext does not panic on a nil context.
func TestBuildAgentPromptNilContext(t *testing.T) {
	if prompt := BuildAgentPrompt(nil); prompt == "" {
		t.Fatal("nil context produced an empty prompt")
	}
}

// TestPrettyJSONMatchesPython compares the Python-compatible encoder against
// json.dumps(..., ensure_ascii=False, indent=2, sort_keys=True) output.
func TestPrettyJSONMatchesPython(t *testing.T) {
	cases := decodeFixture[map[string]struct {
		Value    any    `json:"value"`
		Expected string `json:"expected"`
	}](t, "testdata/json_cases.json")
	if len(cases) == 0 {
		t.Fatal("json fixtures are empty")
	}
	for name, testCase := range cases {
		t.Run(name, func(t *testing.T) {
			if got := prettyJSON(testCase.Value); got != testCase.Expected {
				t.Errorf("prettyJSON mismatch\n--- want ---\n%s\n--- got ---\n%s", testCase.Expected, got)
			}
		})
	}
}

// TestDescribeTools mirrors ToolRegistry.describe.
func TestDescribeTools(t *testing.T) {
	registry := tools.BuildDefaultRegistry()
	described := DescribeTools(registry)
	if len(described) != len(registry.Names()) {
		t.Fatalf("described %d tools, registry has %d", len(described), len(registry.Names()))
	}
	for index, entry := range described {
		if domain.StringFrom(entry["name"]) != registry.Names()[index] {
			t.Fatalf("describe order mismatch at %d: %v vs %s", index, entry["name"], registry.Names()[index])
		}
		if _, ok := entry["description"]; !ok {
			t.Fatalf("described tool %v has no description", entry["name"])
		}
	}
	if len(DescribeTools(nil)) != 0 {
		t.Fatal("DescribeTools(nil) should be empty")
	}
}
